name: ci
run-name: ${{ github.actor }} is running ci

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with container registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.CR_USER }}
          registry: ${{ vars.CR_REGISTRY }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.CR_REGISTRY }}/${{ vars.CR_OWNER }}/seal-c:latest
          secrets: |
            signid=${{ secrets.SIGNMYDATA_ID }}
            apikey=${{ secrets.SIGNMYDATA_APIKEY }}

